[package]
name = "MultiTool"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
subprocess = "0.2.9"
rustc-serialize = "0.3.25"
winver = "1.0.0"
